name: clinique
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^0.5.21
  geolocator: 7.0.3
  shared_preferences: 2.0.6
  lottie: ^1.1.0
  gradient_widgets: ^0.6.0
  dio: ^4.0.1
  firebase_storage: ^10.1.0
  flutter_polyline_points: ^1.0.0
  firebase_messaging: ^11.2.3
  flutter_local_notifications: ^9.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  firebase_core: 1.10.0
  firebase_analytics: 8.1.2
  firebase_auth: 2.0.0

  cloud_firestore: 2.3.0
  firebase_database: 7.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/images/
