name: clinique
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cached_network_image: ^3.2.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.1
  equatable: ^2.0.3
  firebase_messaging: ^11.2.3
  firebase_storage: ^10.1.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^9.2.0
  flutter_polyline_points: ^1.0.0
  flutter_rating_bar: ^4.0.0
  geolocator: ^8.2.0
  get: ^4.6.1
  google_maps_flutter: ^2.1.1
  gradient_widgets: ^0.6.0
  lottie: ^1.1.0
  shared_preferences: ^2.0.13
  styled_widget: ^0.4.0+3
  syncfusion_flutter_calendar: ^19.4.43

dev_dependencies:
  cloud_firestore: ^3.1.8
  firebase_analytics: ^9.1.0
  firebase_auth: ^3.3.7

  firebase_core: ^1.12.0
  firebase_database: ^9.0.6
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/images/
